interpreter: main.cpp est.cpp activation.cpp interpreter.cpp ../parser/ast.cpp ../parser/dump_reader.cpp library.cpp
	g++ main.cpp est.cpp activation.cpp interpreter.cpp ../parser/ast.cpp ../parser/dump_reader.cpp library.cpp
